<?php

namespace app\modules\admin\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\web\UploadedFile;

/**
 * This is the model class for table "promo".
 *
 * @property int $id
 * @property string $title
 * @property string $sale
 * @property string $img
 * @property string $created_at
 * @property string $updeted_at
 */
class Promo extends ActiveRecord
{
    public $file;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'promo';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updeted_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updeted_at'],
                ],
                // если вместо метки времени UNIX используется datetime:
                'value' => new Expression('NOW()'),
            ],
        ];
    }
    public function rules()
    {
        return [
            [['title', 'sale', 'img'], 'required'],
            [['created_at', 'updeted_at'], 'safe'],
            [['title'], 'string', 'max' => 255],
            [['img'], 'default', 'value' => 'images/products/no-image.png'],
            [['sale'], 'string', 'max' => 250],
            [['file'], 'image'],
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название ',
            'sale' => 'Скидка',
            'img' => 'Картинка',
            'created_at' => 'Добавлено',
            'updeted_at' => 'Редакторовано',
            'file' => 'Картинка',
        ];
    }

    public function beforeSave($insert)
    {
        if ($file = UploadedFile::getInstance($this, 'file')) {
            $dir = 'images/promo/' . date("Y-m-d") . '/';
            if (!is_dir($dir)) {
                mkdir($dir);
            }
            $file_name = uniqid() . '_' . $file->baseName . '.' . $file->extension;
            $this->img = $dir . $file_name;
            $file->saveAs($this->img);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
