<?php

namespace app\modules\admin\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "team".
 *
 * @property int $id
 * @property string $name
 * @property string $position
 * @property string $img
 * @property string $faceboock
 * @property string $twitter
 * @property string $google
 * @property string $vk
 * @property string $instagram
 * @property string $surname
 */
class Team extends \yii\db\ActiveRecord
{
    public $file;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'team';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'position'], 'required'],
            [['name', 'position', 'faceboock', 'twitter', 'google', 'vk', 'instagram', 'surname'], 'string', 'max' => 250],
            [['img'], 'default', 'value'=> 'images/No_Image.png'],
            [['file'], 'image'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'ФИО',
            'position' => 'Должность',
            'img' => 'Фотография',
            'faceboock' => 'Faceboock',
            'twitter' => 'Twitter',
            'google' => 'Google',
            'vk' => 'Vk',
            'instagram' => 'Instagram',
            'surname' => 'Surname',
            'file' => 'Фотография',
        ];
    }
    public function beforeSave($insert)
    {
        if ($file = UploadedFile::getInstance($this, 'file')) {
            $dir = 'images/team/' . date("Y-m-d") . '/';
            if (!is_dir($dir)) {
                mkdir($dir);
            }
            $file_name = uniqid() . '_' . $file->baseName . '.' . $file->extension;
            $this->img = $dir . $file_name;
            $file->saveAs($this->img);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
